f = open('data1.txt', 'a+')
print(f.tell())
f.seek(0)
print(f.read())
f.write('This is next line\n')
f.seek(0)
print(f.read())
f.seek(0)
f.write('This is last line\n')
f.seek(0)
print(f.read())
f.close()

f = open('data1.txt', 'r+')
print(f.tell())
f.seek(0, 2)
f.write('This is a new line\n')
f.seek(0)
print(f.read())
f.close()
